#!/usr/bin/env node
// Claude Code 省钱报告 / savings report
// Answers "how much did automatic model routing actually save me?" from the local
// Claude Code transcripts (~/.claude/projects/**/*.jsonl). Read-only: never writes to
// any Claude Code file. The only file it may write is the Markdown report (--md).
//
//   node report.js                 terminal report, last 7 days
//   node report.js --days 30       last 30 days
//   node report.js --since 2026-10-01
//   node report.js --md [file]     shareable Markdown report
//   node report.js --json          machine-readable output
//   node report.js --lang zh|en    choose language
'use strict';
const fs = require('fs');
const path = require('path');
const os = require('os');
const readline = require('readline');

const REPO_URL = 'https://github.com/paxon-yang/claude-agent-tools';
const DEFAULT_PRICES = {
  haiku: { in: 0.10, out: 0.50 },
  sonnet: { in: 2, out: 10 },
  opus: { in: 4, out: 20 },
  fable: { in: 10, out: 50, cacheRead: 0.25, cacheWrite: 12.5 },
};
const FAMILIES = ['fable', 'mythos', 'opus', 'sonnet', 'haiku'];
const FAMILY_ORDER = ['haiku', 'sonnet', 'opus', 'fable', 'mythos', 'unpriced'];
const DISPLAY = { haiku: 'Haiku', sonnet: 'Sonnet', opus: 'Opus', fable: 'Fable', mythos: 'Mythos' };

// ---------- 文案 / strings ----------
const T = {
  en: {
    title: 'Claude Code · model routing savings',
    mdTitle: 'How much automatic model routing saved me',
    lastDays: n => `Last ${n} day${n === 1 ? '' : 's'}`,
    since: d => `Since ${d}`,
    range: (a, b) => `${a} → ${b}`,
    period: (l, r) => `${l} (${r})`,
    sessions: n => `${n} session${n === 1 ? '' : 's'}`,
    replies: n => `${fmtInt(n)} model repl${n === 1 ? 'y' : 'ies'}`,
    model: 'Model', msgs: 'Replies', input: 'Input', cacheRead: 'Cache read', cacheWrite: 'Cache write',
    output: 'Output', cost: 'Est. cost', share: 'Share', total: 'Total', unpriced: 'Other (no price)',
    actual: 'Estimated cost', allOn: m => `All on ${m}`, saved: 'Saved',
    headline: (p, c, b, m) => `Saved ${p} — ${c} instead of about ${b} if everything ran on ${m}.`,
    savedLine: (p, amt) => `${p} (${amt})`,
    neutralSame: (m, c) => `Everything here ran on ${m} (or something priced like it), so it cost the same as the all-${m} baseline: about ${c}.`,
    neutralMore: (m, c, b) => `This period cost about ${c}, more than running everything on ${m} would have (about ${b}), because some turns used a pricier model.`,
    noData: 'No Claude Code usage found in this period.',
    noBaseline: m => `Can't compare: no price is set for the baseline model "${m}".`,
    routedTitle: 'Sessions routed by auto-router vs. other sessions',
    routedRow: 'Routed by auto-router', otherRow: 'Other sessions',
    colSessions: 'Sessions', colBaseline: m => `All on ${m}`, colSaved: 'Saved',
    routedNote: 'auto-router keeps a small note for every session it routed; sessions without one are counted as "other".',
    topTitle: 'Most expensive sessions', project: 'Project', session: 'Session', mainModel: 'Mostly',
    unpricedNote: n => n === 1 ? '1 reply came from a model without a price; it is listed but not included in the cost or savings.'
      : `${fmtInt(n)} replies came from models without a price; they are listed but not included in the cost or savings.`,
    method: m => `Estimated at public API list prices; if you use a subscription this is an equivalent value, not your bill. Baseline = same tokens priced as ${m}.`,
    footer: `Generated by claude-agent-tools — ${REPO_URL}`,
    wrote: f => `Wrote ${f}`,
    na: '—',
  },
  zh: {
    title: 'Claude Code · 自动选模型省了多少',
    mdTitle: '自动选模型帮我省了多少',
    lastDays: n => `近 ${n} 天`,
    since: d => `${d} 以来`,
    range: (a, b) => `${a} 至 ${b}`,
    period: (l, r) => `${l}（${r}）`,
    sessions: n => `${n} 个会话`,
    replies: n => `模型回复 ${fmtInt(n)} 次`,
    model: '模型', msgs: '回复次数', input: '输入', cacheRead: '缓存读取', cacheWrite: '缓存写入',
    output: '输出', cost: '估算花费', share: '占比', total: '合计', unpriced: '其他（无价格）',
    actual: '实际约', allOn: m => `全用 ${m} 约`, saved: '少花',
    headline: (p, c, b, m) => `少花 ${p}：实际约 ${c}，同样的活全用 ${m} 约 ${b}。`,
    savedLine: (p, amt) => `${p}（省下 ${amt}）`,
    neutralSame: (m, c) => `这段时间都在用 ${m}（或同价的模型），跟全用 ${m} 花的一样，约 ${c}。`,
    neutralMore: (m, c, b) => `这段时间约花 ${c}，比全用 ${m}（约 ${b}）还多，因为有些回合用了更贵的模型。`,
    noData: '这段时间没有找到 Claude Code 的用量记录。',
    noBaseline: m => `没法对比：对照模型"${m}"没有设置价格。`,
    routedTitle: '自动选模型接管的会话 vs 其他会话',
    routedRow: '自动选模型接管的', otherRow: '其他会话',
    colSessions: '会话数', colBaseline: m => `全用 ${m} 约`, colSaved: '少花',
    routedNote: '自动选模型会给它接管过的会话留一条小记录；没有记录的会话算作"其他"。',
    topTitle: '花费最多的会话', project: '项目', session: '会话', mainModel: '主要用',
    unpricedNote: n => `有 ${fmtInt(n)} 次回复来自没有价格的模型，只列出，不算进花费和节省。`,
    method: m => `按官方 API 公开价格估算；如果你用的是订阅套餐，这是等值金额，不是你的账单。对照 = 同样的 token 全按 ${m} 计价。`,
    footer: `由 claude-agent-tools 生成 — ${REPO_URL}`,
    wrote: f => `已写入 ${f}`,
    na: '—',
  },
};

const HELP = {
  en: `Claude Code savings report — how much did automatic model routing save you?

Usage: node report.js [options]

  --days N          look at the last N days (default 7)
  --since DATE      look at everything since DATE (YYYY-MM-DD, local time)
  --md [file]       write a shareable Markdown report
                    (default ./claude-savings-YYYY-MM-DD.md; use "-" for stdout)
  --no-projects     leave project names out of the report
  --json            print machine-readable JSON
  --lang en|zh      language (default: CAT_LANG, then system language)
  --config PATH     price config (default ~/.claude/viz/app/config.json,
                    then config.json next to this script)
  --home DIR        use DIR instead of your home folder (for testing)
  -h, --help        show this help

Reads ~/.claude/projects/**/*.jsonl only. Nothing is changed or uploaded.
Costs are estimates at public API list prices.`,
  zh: `Claude Code 省钱报告 —— 看看自动选模型到底帮你省了多少

用法：node report.js [选项]

  --days N          看最近 N 天（默认 7 天）
  --since 日期      看某天以来（格式 YYYY-MM-DD）
  --md [文件]       生成可以分享的 Markdown 报告
                    （默认 ./claude-savings-年-月-日.md；写 "-" 则直接打印）
  --no-projects     报告里不写项目名
  --json            输出 JSON（给程序用）
  --lang en|zh      语言（默认看 CAT_LANG，再看系统语言）
  --config 路径     价格配置（默认 ~/.claude/viz/app/config.json，
                    其次是本脚本旁边的 config.json）
  --home 目录       把这个目录当作用户主目录（测试用）
  -h, --help        显示帮助

只读取 ~/.claude/projects 下的会话记录，不修改、不上传任何东西。
金额按官方 API 公开价格估算。`,
};

// ---------- 参数 / args ----------
function parseArgs(argv) {
  const o = { days: null, since: null, md: false, mdFile: null, json: false, lang: null, config: null, home: null, help: false, projects: true };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    const next = () => { const v = argv[i + 1]; if (v == null) die(`Missing value for ${a}`); i++; return v; };
    if (a === '-h' || a === '--help') o.help = true;
    else if (a === '--days') o.days = next();
    else if (a.startsWith('--days=')) o.days = a.slice(7);
    else if (a === '--since') o.since = next();
    else if (a.startsWith('--since=')) o.since = a.slice(8);
    else if (a === '--md') { o.md = true; const v = argv[i + 1]; if (v != null && (v === '-' || !v.startsWith('-'))) { o.mdFile = v; i++; } }
    else if (a.startsWith('--md=')) { o.md = true; o.mdFile = a.slice(5); }
    else if (a === '--json') o.json = true;
    else if (a === '--lang') o.lang = next();
    else if (a.startsWith('--lang=')) o.lang = a.slice(7);
    else if (a === '--config') o.config = next();
    else if (a.startsWith('--config=')) o.config = a.slice(9);
    else if (a === '--home') o.home = next();
    else if (a.startsWith('--home=')) o.home = a.slice(7);
    else if (a === '--no-projects') o.projects = false;
    else die(`Unknown option: ${a}  (try --help)`);
  }
  return o;
}
function die(msg) { process.stderr.write(msg + '\n'); process.exit(2); }

function detectLang(opt) {
  const norm = v => { v = String(v || '').toLowerCase(); return v.startsWith('zh') ? 'zh' : v.startsWith('en') ? 'en' : null; };
  if (opt && norm(opt)) return norm(opt);
  if (norm(process.env.CAT_LANG)) return norm(process.env.CAT_LANG);
  for (const k of ['LC_ALL', 'LC_MESSAGES', 'LANG']) {
    const v = process.env[k];
    if (v && v !== 'C' && v !== 'POSIX' && !v.startsWith('C.')) return String(v).toLowerCase().startsWith('zh') ? 'zh' : 'en';
  }
  if (process.platform === 'darwin') {
    try {
      const out = require('child_process').execFileSync('defaults', ['read', '-g', 'AppleLanguages'],
        { encoding: 'utf8', timeout: 2000, stdio: ['ignore', 'pipe', 'ignore'] });
      const m = out.match(/[A-Za-z]{2,3}(?:[-_][A-Za-z0-9]+)*/);
      if (m && m[0].toLowerCase().startsWith('zh')) return 'zh';
    } catch { /* ignore */ }
  }
  return 'en';
}

// ---------- 配置与价格 / config & prices ----------
function readJSON(p) { try { return JSON.parse(fs.readFileSync(p, 'utf8')); } catch { return null; } }
function loadConfig(opt, home) {
  const candidates = opt.config ? [opt.config] : [path.join(home, '.claude', 'viz', 'app', 'config.json'), path.join(__dirname, 'config.json')];
  for (const p of candidates) {
    if (!fs.existsSync(p)) { if (opt.config) die(`Config not found: ${p}`); continue; }
    const c = readJSON(p);
    if (c) return { cfg: c, from: p };
    if (opt.config) die(`Config is not valid JSON: ${p}`);
  }
  return { cfg: {}, from: null };
}
function buildPrices(cfg) {
  const prices = {};
  for (const k of Object.keys(DEFAULT_PRICES)) prices[k] = Object.assign({}, DEFAULT_PRICES[k]);
  const over = cfg && cfg.prices && typeof cfg.prices === 'object' ? cfg.prices : {};
  for (const k of Object.keys(over)) prices[k] = Object.assign({}, prices[k] || {}, over[k] || {});
  return prices;
}
function family(model) {
  if (!model) return null;
  const s = String(model).toLowerCase();
  return FAMILIES.find(f => s.includes(f)) || null;
}
function priceOf(prices, fam) {
  let p = prices[fam];
  if ((!p || p.in == null) && fam === 'mythos') p = prices.fable;
  if (!p || p.in == null || p.out == null) return null;
  const pin = Number(p.in), pout = Number(p.out);
  return { in: pin, out: pout, cr: p.cacheRead != null ? Number(p.cacheRead) : pin * 0.1, cw: p.cacheWrite != null ? Number(p.cacheWrite) : pin * 1.25 };
}
function costOf(u, p) { return p ? (u.in * p.in + u.out * p.out + u.cr * p.cr + u.cw * p.cw) / 1e6 : null; }

// ---------- 读取会话记录 / scan transcripts ----------
function listJsonl(dir) {
  const out = [];
  const walk = d => {
    let ents; try { ents = fs.readdirSync(d, { withFileTypes: true }); } catch { return; }
    for (const e of ents) {
      const p = path.join(d, e.name);
      if (e.isDirectory()) walk(p);
      else if (e.isFile() && e.name.endsWith('.jsonl')) out.push(p);
    }
  };
  walk(dir);
  return out.sort();
}
const UUIDISH = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
function sessionFromPath(file, projectsDir) {
  const rel = path.relative(projectsDir, file).split(path.sep);
  // rel: [projectDir, ...rest]
  const base = path.basename(file, '.jsonl');
  if (!base.startsWith('agent-')) return base;
  // <project>/<session>/subagents/agent-x.jsonl  or <project>/<session>/agent-x.jsonl
  for (let i = rel.length - 2; i >= 1; i--) if (rel[i] !== 'subagents') return rel[i];
  return base;
}

async function scan(home, startMs, endMs) {
  const projectsDir = path.join(home, '.claude', 'projects');
  const files = listJsonl(projectsDir);
  const messages = new Map();   // key -> record (last one seen wins)
  const projectCwd = new Map(); // project dir name -> cwd basename
  const stats = { filesFound: files.length, filesScanned: 0, filesSkippedOld: 0, badLines: 0, syntheticSkipped: 0 };
  for (const file of files) {
    let st; try { st = fs.statSync(file); } catch { continue; }
    if (st.mtimeMs < startMs) { stats.filesSkippedOld++; continue; }
    stats.filesScanned++;
    const projDir = path.relative(projectsDir, file).split(path.sep)[0];
    const fileSession = sessionFromPath(file, projectsDir);
    const stream = fs.createReadStream(file, { encoding: 'utf8' });
    const rl = readline.createInterface({ input: stream, crlfDelay: Infinity });
    try {
      for await (const raw of rl) {
        const hasUsage = raw.includes('"usage"');
        const wantCwd = !projectCwd.has(projDir) && raw.includes('"cwd"');
        if (!hasUsage && !wantCwd) continue;
        let o;
        try { o = JSON.parse(raw); } catch { stats.badLines++; continue; }
        if (!o || typeof o !== 'object') continue;
        if (typeof o.cwd === 'string' && o.cwd && !projectCwd.has(projDir)) projectCwd.set(projDir, baseName(o.cwd));
        if (o.type !== 'assistant' || !o.message || typeof o.message !== 'object') continue;
        const m = o.message, u = m.usage;
        if (!u || typeof u !== 'object') continue;
        const model = typeof m.model === 'string' ? m.model : '';
        if (model.startsWith('<')) { stats.syntheticSkipped++; continue; }
        const key = m.id || o.uuid;
        if (!key) continue;
        const ts = Date.parse(o.timestamp);
        messages.set(key, {
          model, fam: family(model),
          ts: Number.isFinite(ts) ? ts : st.mtimeMs,
          session: typeof o.sessionId === 'string' && o.sessionId ? o.sessionId : fileSession,
          projDir,
          sidechain: !!o.isSidechain,
          mainFile: !path.basename(file).startsWith('agent-'),
          in: num(u.input_tokens), out: num(u.output_tokens),
          cr: num(u.cache_read_input_tokens), cw: num(u.cache_creation_input_tokens),
        });
      }
    } catch { /* unreadable file: skip the rest */ } finally { rl.close(); stream.destroy(); }
  }
  const recs = [];
  for (const r of messages.values()) if (r.ts >= startMs && r.ts <= endMs + 60000) recs.push(r);
  return { recs, projectCwd, stats };
}
function num(v) { v = Number(v); return Number.isFinite(v) && v > 0 ? v : 0; }
function baseName(p) { const parts = String(p).split(/[\\/]+/).filter(Boolean); return parts.length ? parts[parts.length - 1] : String(p); }

function routedSessions(home) {
  const dir = path.join(home, '.claude', 'viz', 'router');
  let ents; try { ents = fs.readdirSync(dir); } catch { return null; }
  const set = new Set();
  for (const n of ents) if (n.endsWith('.json')) set.add(n.slice(0, -5));
  return set;
}

// ---------- 汇总 / aggregate ----------
function emptyAgg() { return { messages: 0, in: 0, out: 0, cr: 0, cw: 0 }; }
function addTo(a, r) { a.messages++; a.in += r.in; a.out += r.out; a.cr += r.cr; a.cw += r.cw; }

function summarize(recs, prices, baselineModel) {
  const bp = priceOf(prices, family(baselineModel) || String(baselineModel).toLowerCase());
  const byFam = {}, rawModels = {};
  let cost = 0, baseline = 0, unpricedMessages = 0;
  const total = emptyAgg();
  for (const r of recs) {
    const k = r.fam || 'unpriced';
    addTo(byFam[k] || (byFam[k] = emptyAgg()), r);
    addTo(total, r);
    rawModels[r.model || '(unknown)'] = (rawModels[r.model || '(unknown)'] || 0) + 1;
  }
  const models = [];
  for (const k of Object.keys(byFam).sort((a, b) => FAMILY_ORDER.indexOf(a) - FAMILY_ORDER.indexOf(b))) {
    const a = byFam[k];
    const p = k === 'unpriced' ? null : priceOf(prices, k);
    const c = costOf(a, p);
    const b = c == null ? null : costOf(a, bp);
    if (c == null) unpricedMessages += a.messages;
    else { cost += c; if (b != null) baseline += b; }
    models.push({ family: k, name: DISPLAY[k] || null, messages: a.messages, input: a.in, cacheRead: a.cr, cacheWrite: a.cw, output: a.out, cost: c, baseline: b });
  }
  for (const m of models) m.share = m.cost != null && cost > 0 ? m.cost / cost : (m.cost != null ? 0 : null);
  return { total, models, rawModels, cost, baseline: bp ? baseline : null, unpricedMessages, verdict: verdict(cost, bp ? baseline : null, total.messages) };
}
function verdict(cost, baseline, messages) {
  if (!messages) return { kind: 'nodata', saved: null, savedAmount: null };
  if (baseline == null) return { kind: 'nobaseline', saved: null, savedAmount: null };
  if (!(baseline > 0)) return { kind: 'nodata', saved: null, savedAmount: null };
  const saved = 1 - cost / baseline;
  if (saved >= 0.005) return { kind: 'saved', saved, savedAmount: baseline - cost };
  if (saved > -0.005) return { kind: 'same', saved, savedAmount: baseline - cost };
  return { kind: 'more', saved, savedAmount: baseline - cost };
}

function groupSessions(recs, prices, baselineModel, projectCwd) {
  const bp = priceOf(prices, family(baselineModel) || String(baselineModel).toLowerCase());
  const map = new Map();
  for (const r of recs) {
    let s = map.get(r.session);
    if (!s) map.set(r.session, s = { id: r.session, projDir: r.projDir, rank: -1, recs: [], last: 0 });
    s.recs.push(r);
    if (r.ts > s.last) s.last = r.ts;
    // 项目名优先取主会话文件所在的目录 / prefer the folder of the session's own transcript
    const rank = (r.mainFile ? 2 : 0) + (r.sidechain ? 0 : 1);
    if (rank > s.rank) { s.rank = rank; s.projDir = r.projDir; }
  }
  const out = [];
  for (const s of map.values()) {
    let cost = 0, baseline = 0;
    const famCost = {};
    for (const r of s.recs) {
      const c = r.fam ? costOf(r, priceOf(prices, r.fam)) : null;
      if (c == null) continue;
      cost += c;
      const b = costOf(r, bp); if (b != null) baseline += b;
      famCost[r.fam] = (famCost[r.fam] || 0) + c;
    }
    const main = Object.keys(famCost).sort((a, b) => famCost[b] - famCost[a])[0] || null;
    out.push({ sessionId: s.id, project: projectCwd.get(s.projDir) || s.projDir, messages: s.recs.length, cost, baseline: bp ? baseline : null,
      mainFamily: main, mainShare: main && cost > 0 ? famCost[main] / cost : null, lastActivity: new Date(s.last).toISOString() });
  }
  return out.sort((a, b) => b.cost - a.cost);
}

async function buildReport(opt) {
  const home = path.resolve(opt.home || os.homedir());
  const { cfg, from } = loadConfig(opt, home);
  const prices = buildPrices(cfg);
  const baselineModel = String(cfg.baselineModel || 'opus');
  const nowMs = Date.now();
  let startMs, days = null, since = null;
  if (opt.since) {
    const m = String(opt.since).match(/^(\d{4})-(\d{1,2})-(\d{1,2})$/);
    if (!m) die('--since expects YYYY-MM-DD');
    startMs = new Date(+m[1], +m[2] - 1, +m[3]).getTime();
    since = ymd(new Date(startMs));
  } else {
    days = opt.days == null ? 7 : Number(opt.days);
    if (!(days > 0)) die('--days expects a positive number');
    startMs = nowMs - days * 86400000;
  }
  const { recs, projectCwd, stats } = await scan(home, startMs, nowMs);
  const sum = summarize(recs, prices, baselineModel);
  const sessions = groupSessions(recs, prices, baselineModel, projectCwd);
  const routedSet = routedSessions(home);
  let routed = null;
  if (routedSet) {
    const part = pred => {
      const rs = recs.filter(r => pred(routedSet.has(r.session)));
      const s = summarize(rs, prices, baselineModel);
      return { sessions: new Set(rs.map(r => r.session)).size, messages: s.total.messages, cost: s.cost, baseline: s.baseline,
        saved: s.verdict.saved, savedAmount: s.verdict.savedAmount, verdict: s.verdict.kind };
    };
    routed = { routed: part(x => x), other: part(x => !x) };
  }
  const bfam = family(baselineModel) || baselineModel.toLowerCase();
  return {
    version: 1,
    generatedAt: new Date(nowMs).toISOString(),
    period: { start: new Date(startMs).toISOString(), end: new Date(nowMs).toISOString(), days, since },
    baselineModel: bfam,
    baselineName: DISPLAY[bfam] || baselineModel,
    prices, configFrom: from ? (from.startsWith(home) ? '~' + from.slice(home.length) : path.basename(from)) : null,
    totals: {
      sessions: sessions.length, messages: sum.total.messages,
      input: sum.total.in, cacheRead: sum.total.cr, cacheWrite: sum.total.cw, output: sum.total.out,
      cost: sum.cost, baseline: sum.baseline, saved: sum.verdict.saved, savedAmount: sum.verdict.savedAmount,
      verdict: sum.verdict.kind, unpricedMessages: sum.unpricedMessages,
    },
    models: sum.models,
    rawModels: sum.rawModels,
    routed,
    topSessions: sessions.slice(0, 5),
    scan: stats,
  };
}

// ---------- 格式化 / formatting ----------
function fmtInt(n) { return Math.round(n).toLocaleString('en-US'); }
function fmtTok(n, lang) {
  if (lang === 'zh') {
    if (n < 10000) return fmtInt(n);
    if (n < 1e8) return trimNum(n / 1e4, n < 1e5 ? 1 : 0) + '万';
    return trimNum(n / 1e8, 2) + '亿';
  }
  if (n < 1000) return fmtInt(n);
  if (n < 1e6) return trimNum(n / 1e3, n < 1e4 ? 1 : 0) + 'k';
  if (n < 1e9) return trimNum(n / 1e6, n < 1e7 ? 2 : 1) + 'M';
  return trimNum(n / 1e9, 2) + 'B';
}
function trimNum(v, d) { return v.toFixed(d).replace(/\.0+$/, '').replace(/(\.\d*?)0+$/, '$1'); }
function money(v) {
  if (v == null) return '—';
  if (v === 0) return '$0';
  if (Math.abs(v) < 0.01) return '<$0.01';
  if (Math.abs(v) >= 1000) return '$' + Math.round(v).toLocaleString('en-US');
  return '$' + v.toFixed(2);
}
function pct(v) { return v == null ? '—' : (Math.abs(v) < 0.01 && v !== 0 ? '<1%' : Math.round(v * 100) + '%'); }
function ymd(d) { return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`; }
function famName(f, t) { return f === 'unpriced' ? t.unpriced : (DISPLAY[f] || f); }
function periodLabel(rep, t) {
  const a = ymd(new Date(rep.period.start)), b = ymd(new Date(rep.period.end));
  return t.period(rep.period.since ? t.since(rep.period.since) : t.lastDays(rep.period.days), t.range(a, b));
}

function cellWidth(s) {
  let w = 0;
  for (const ch of String(s)) {
    const c = ch.codePointAt(0);
    w += (c >= 0x1100 && (c <= 0x115f || (c >= 0x2e80 && c <= 0xa4cf) || (c >= 0xac00 && c <= 0xd7a3) || (c >= 0xf900 && c <= 0xfaff) || (c >= 0xfe30 && c <= 0xfe4f) || (c >= 0xff00 && c <= 0xff60) || (c >= 0xffe0 && c <= 0xffe6))) ? 2 : 1;
  }
  return w;
}
function pad(s, w, right) { s = String(s); const n = Math.max(0, w - cellWidth(s)); return right ? ' '.repeat(n) + s : s + ' '.repeat(n); }
function table(rows, rightCols, styleRow) {
  const widths = [];
  for (const r of rows) r.forEach((c, i) => { widths[i] = Math.max(widths[i] || 0, cellWidth(c)); });
  return rows.map((r, ri) => {
    const line = r.map((c, i) => pad(c, widths[i], rightCols.includes(i))).join('  ').replace(/\s+$/, '');
    return styleRow ? styleRow(line, ri) : line;
  });
}

function verdictText(v, t, base, cost, baseline) {
  if (v === 'nodata') return t.noData;
  if (v === 'nobaseline') return t.noBaseline(base);
  if (v === 'same') return t.neutralSame(base, money(cost));
  if (v === 'more') return t.neutralMore(base, money(cost), money(baseline));
  return null;
}

function renderTerminal(rep, lang, color) {
  const t = T[lang];
  const C = (code, s) => color ? `\x1b[${code}m${s}\x1b[0m` : s;
  const bold = s => C('1', s), dim = s => C('2', s), green = s => C('32', s);
  const L = [];
  const base = rep.baselineName, tot = rep.totals;
  L.push(bold(t.title));
  L.push(dim(`${periodLabel(rep, t)} · ${t.sessions(tot.sessions)} · ${t.replies(tot.messages)}`));
  L.push('');
  if (!tot.messages) { L.push(t.noData); return L.join('\n') + '\n'; }

  const head = [t.model, t.msgs, t.input, t.cacheRead, t.cacheWrite, t.output, t.cost, t.share];
  const rows = [head];
  for (const m of rep.models) rows.push([famName(m.family, t), fmtInt(m.messages), fmtTok(m.input, lang), fmtTok(m.cacheRead, lang), fmtTok(m.cacheWrite, lang), fmtTok(m.output, lang), money(m.cost), pct(m.share)]);
  rows.push([t.total, fmtInt(tot.messages), fmtTok(tot.input, lang), fmtTok(tot.cacheRead, lang), fmtTok(tot.cacheWrite, lang), fmtTok(tot.output, lang), money(tot.cost), tot.cost > 0 ? '100%' : '—']);
  const last = rows.length - 1;
  L.push(...table(rows, [1, 2, 3, 4, 5, 6, 7], (line, i) => i === 0 ? dim(line) : i === last ? bold(line) : line).map(s => '  ' + s));
  L.push('');

  const v = tot.verdict;
  if (v === 'saved') {
    const kv = table([[t.actual, money(tot.cost)], [t.allOn(base), money(tot.baseline)], [t.saved, t.savedLine(pct(tot.saved), money(tot.savedAmount))]], [1]);
    L.push('  ' + kv[0], '  ' + kv[1], '  ' + green(bold(kv[2])));
  } else {
    L.push('  ' + verdictText(v, t, base, tot.cost, tot.baseline));
  }
  if (tot.unpricedMessages) L.push('  ' + dim(t.unpricedNote(tot.unpricedMessages)));

  if (rep.routed) {
    L.push('', bold(t.routedTitle));
    const r = [[' ', t.colSessions, t.cost, t.colBaseline(base), t.colSaved]];
    for (const [k, lab] of [['routed', t.routedRow], ['other', t.otherRow]]) {
      const p = rep.routed[k];
      r.push([lab, String(p.sessions), money(p.cost), money(p.baseline), p.verdict === 'saved' ? pct(p.saved) : '—']);
    }
    L.push(...table(r, [1, 2, 3, 4], (line, i) => i === 0 ? dim(line) : line).map(s => '  ' + s));
    L.push('  ' + dim(t.routedNote));
  }

  if (rep.topSessions.length) {
    L.push('', bold(t.topTitle));
    const r = [['#', t.project, t.session, t.cost, t.mainModel]];
    rep.topSessions.forEach((s, i) => r.push([String(i + 1), s.project, s.sessionId.slice(0, 8), money(s.cost), s.mainFamily ? `${famName(s.mainFamily, t)} ${pct(s.mainShare)}` : '—']));
    L.push(...table(r, [0, 3], (line, i) => i === 0 ? dim(line) : line).map(s => '  ' + s));
  }
  L.push('', dim(t.method(base)));
  return L.join('\n') + '\n';
}

function mdEsc(s) { return String(s).replace(/\|/g, '\\|').replace(/[<>]/g, c => (c === '<' ? '&lt;' : '&gt;')); }
function renderMarkdown(rep, lang, withProjects) {
  const t = T[lang];
  const base = rep.baselineName, tot = rep.totals;
  const L = [];
  L.push(`# ${t.mdTitle}`, '');
  L.push(`**${periodLabel(rep, t)}** · ${t.sessions(tot.sessions)} · ${t.replies(tot.messages)}`, '');
  if (tot.verdict === 'saved') L.push(`> **${t.headline(pct(tot.saved), money(tot.cost), money(tot.baseline), base)}**`, '');
  else L.push(`> ${verdictText(tot.verdict, t, base, tot.cost, tot.baseline)}`, '');
  if (tot.messages) {
    L.push(`| ${[t.model, t.msgs, t.input, t.cacheRead, t.cacheWrite, t.output, t.cost, t.share].join(' | ')} |`);
    L.push('|---|---:|---:|---:|---:|---:|---:|---:|');
    for (const m of rep.models) L.push(`| ${famName(m.family, t)} | ${fmtInt(m.messages)} | ${fmtTok(m.input, lang)} | ${fmtTok(m.cacheRead, lang)} | ${fmtTok(m.cacheWrite, lang)} | ${fmtTok(m.output, lang)} | ${mdEsc(money(m.cost))} | ${pct(m.share)} |`);
    L.push(`| **${t.total}** | **${fmtInt(tot.messages)}** | **${fmtTok(tot.input, lang)}** | **${fmtTok(tot.cacheRead, lang)}** | **${fmtTok(tot.cacheWrite, lang)}** | **${fmtTok(tot.output, lang)}** | **${mdEsc(money(tot.cost))}** | ${tot.cost > 0 ? '100%' : '—'} |`, '');
    if (tot.verdict === 'saved') {
      const sep = lang === 'zh' ? ' ' : ': ';
      L.push(`- ${t.actual}${sep}**${mdEsc(money(tot.cost))}**`);
      L.push(`- ${t.allOn(base)}${sep}**${mdEsc(money(tot.baseline))}**`);
      L.push(`- ${t.saved}${sep}**${mdEsc(t.savedLine(pct(tot.saved), money(tot.savedAmount)))}**`, '');
    }
    if (tot.unpricedMessages) L.push(`_${t.unpricedNote(tot.unpricedMessages)}_`, '');
    if (rep.routed) {
      L.push(`## ${t.routedTitle}`, '');
      L.push(`| | ${t.colSessions} | ${t.cost} | ${t.colBaseline(base)} | ${t.colSaved} |`);
      L.push('|---|---:|---:|---:|---:|');
      for (const [k, lab] of [['routed', t.routedRow], ['other', t.otherRow]]) {
        const p = rep.routed[k];
        L.push(`| ${lab} | ${p.sessions} | ${mdEsc(money(p.cost))} | ${mdEsc(money(p.baseline))} | ${p.verdict === 'saved' ? '**' + pct(p.saved) + '**' : '—'} |`);
      }
      L.push('');
    }
    if (withProjects && rep.topSessions.length) {
      L.push(`## ${t.topTitle}`, '');
      L.push(`| # | ${t.project} | ${t.cost} | ${t.mainModel} |`);
      L.push('|---:|---|---:|---|');
      rep.topSessions.forEach((s, i) => L.push(`| ${i + 1} | ${mdEsc(s.project)} | ${mdEsc(money(s.cost))} | ${s.mainFamily ? `${famName(s.mainFamily, t)} ${pct(s.mainShare)}` : '—'} |`));
      L.push('');
    }
  }
  L.push(`<sub>${mdEsc(t.method(base))}</sub>`, '');
  L.push('---', '', t.footer, '');
  return L.join('\n');
}

function round(v, d) { if (v == null) return v; const f = Math.pow(10, d); return Math.round(v * f) / f; }
function toJSON(rep, withProjects) {
  const r = JSON.parse(JSON.stringify(rep));
  const fix = o => { for (const k of ['cost', 'baseline', 'savedAmount']) if (o && typeof o[k] === 'number') o[k] = round(o[k], 6); for (const k of ['saved', 'share', 'mainShare']) if (o && typeof o[k] === 'number') o[k] = round(o[k], 6); };
  fix(r.totals); r.models.forEach(fix); r.topSessions.forEach(fix);
  if (r.routed) { fix(r.routed.routed); fix(r.routed.other); }
  if (!withProjects) r.topSessions.forEach(s => { delete s.project; });
  return JSON.stringify(r, null, 2) + '\n';
}

// ---------- main ----------
async function main() {
  const opt = parseArgs(process.argv.slice(2));
  const lang = detectLang(opt.lang);
  if (opt.help) { process.stdout.write(HELP[lang] + '\n'); return; }
  const rep = await buildReport(opt);
  if (opt.json) { process.stdout.write(toJSON(rep, opt.projects)); return; }
  if (opt.md) {
    const md = renderMarkdown(rep, lang, opt.projects);
    if (opt.mdFile === '-') { process.stdout.write(md); return; }
    const file = path.resolve(opt.mdFile || `claude-savings-${ymd(new Date())}.md`);
    fs.writeFileSync(file, md);
    process.stdout.write(T[lang].wrote(file) + '\n');
    return;
  }
  const color = !!process.stdout.isTTY && !process.env.NO_COLOR && process.env.TERM !== 'dumb';
  process.stdout.write(renderTerminal(rep, lang, color));
}

if (require.main === module) main().catch(err => { process.stderr.write(String(err && err.stack || err) + '\n'); process.exit(1); });
module.exports = { buildReport, renderTerminal, renderMarkdown, family, priceOf, buildPrices };
