#!/usr/bin/env node
// Builds the static live demo for GitHub Pages (docs/index.html + docs/demo/snapshots.{en,zh}.json).
// It runs the dashboard in --demo mode for each language, records one full playback of the
// snapshots it pushes over SSE, and writes a copy of the dashboard page that replays them.
// Usage: node scripts/build-pages.js
'use strict';
const { spawn } = require('child_process');
const http = require('http');
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const OUT = path.join(ROOT, 'docs');
const SECONDS = 52; // one demo playback is ~44s
const PORTS = { en: 4391, zh: 4392 };

function record(lang) {
  return new Promise((resolve, reject) => {
    const srv = spawn(process.execPath, [path.join(ROOT, 'agent-viz', 'server.js'), '--demo', '--lang', lang, '--port', String(PORTS[lang])],
      { stdio: ['ignore', 'pipe', 'inherit'], env: { ...process.env, CAT_LANG: lang } });
    const frames = [];
    let t0 = null, last = null;
    const done = () => { try { srv.kill(); } catch { } resolve(frames); };
    srv.on('error', reject);
    srv.stdout.once('data', () => {
      http.get({ host: '127.0.0.1', port: PORTS[lang], path: '/api/stream' }, res => {
        let buf = '';
        res.setEncoding('utf8');
        res.on('data', chunk => {
          buf += chunk;
          let i;
          while ((i = buf.indexOf('\n\n')) >= 0) {
            const block = buf.slice(0, i); buf = buf.slice(i + 2);
            const line = block.split('\n').find(l => l.startsWith('data: '));
            if (!line) continue;
            const s = JSON.parse(line.slice(6));
            if (t0 == null) t0 = s.now;
            delete s.lang;
            s.remote = { mode: 'tailscale', urls: [] };
            const key = JSON.stringify({ ...s, now: 0 });
            if (key === last) continue;
            last = key;
            frames.push({ t: Math.round((s.now - t0) * 100) / 100, s });
          }
        });
        setTimeout(() => { res.destroy(); done(); }, SECONDS * 1000);
      }).on('error', reject);
    });
  });
}

(async () => {
  fs.mkdirSync(path.join(OUT, 'demo'), { recursive: true });
  const results = await Promise.all(['en', 'zh'].map(async l => [l, await record(l)]));
  for (const [lang, frames] of results) {
    // drop the frames from a second playback, if the recording ran into one
    const reset = frames.findIndex((f, i) => i > 5 && f.s.sessions.length < frames[i - 1].s.sessions.length);
    const keep = reset > 0 ? frames.slice(0, reset) : frames;
    const file = path.join(OUT, 'demo', `snapshots.${lang}.json`);
    fs.writeFileSync(file, JSON.stringify({ lang, frames: keep }));
    console.log(`${lang}: ${keep.length} frames, ${(fs.statSync(file).size / 1024).toFixed(0)} KB`);
  }
  const page = fs.readFileSync(path.join(ROOT, 'agent-viz', 'public', 'index.html'), 'utf8');
  const head = `<!-- Generated by scripts/build-pages.js from agent-viz/public/index.html. Do not edit. -->
<meta name="description" content="Live demo of agent-viz: watch Claude Code's main session, sub-agents, models and cost in real time.">
<meta property="og:title" content="Claude Agent Tools · live demo">
<meta property="og:description" content="Automatic model routing + a live agent dashboard for Claude Code.">
<meta property="og:image" content="https://paxon-yang.github.io/claude-agent-tools/flow.png">
<script>window.VIZ_STATIC = 'demo/';</script>
`;
  const out = page.replace('</head>', head + '</head>');
  if (out === page) throw new Error('could not inject static flag');
  fs.writeFileSync(path.join(OUT, 'index.html'), out);
  console.log('wrote docs/index.html');
})().catch(e => { console.error(e); process.exit(1); });
